### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [rabbibotton/clog-plotly#1]
Building with SBCL 2.4.6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id a72d419e75ce8547746cfcd867019b7ab86df826

*clog-plotly/tools* fails to build with the following error:

```
Unhandled UNBOUND-VARIABLE in thread #<SB-THREAD:THREAD tid=3515244 "main thread" RUNNING {1000DC8003}>: The variable CLOG-TOOLS::*PROPS-WITH-HEIGHT* is unbound.

```

[Full log here](http://report.quicklisp.org/2024-07-24/failure-report/clog-plotly.html)

**Comment by rabbibotton** [comment]
Fixed! Thanks!!
